---
title: "Shannon Sweeney"
---
## Education 
  - I graduated Benicia High School in 2018. Upon graduating I was one of two students to recieve the award for Overall Excellence.
  - I am currently a student at UC Santa Barbara, majoring in Environmental Studies and minoring in Geography.

## Expierence
- External vice president for local affairs (2018-present)
  - I started working in the EVPLA office as an intern during fall of 2018. In june of last year I was selected by the previous External Vice President of Local Affairs to be the Chief of Staff for the office. The office focuses created a relationship between the Isla Vista government and organizations with the UC Santa Barbara Community. 
- Sprouts Farmers Market (2019-Present)
  - I was hired as the first Sales Ambassador at Sprouts in Goleta, California. As Sales Ambassodor I demoed products, increasing sales and the overall customer satifaction demonstrated through surveys. 
- Pardall Center Governance Board (2020-present)
  - I was selected to serve as the Student Representative at Large for the Pardall Center Governance Board. I am part of the voting members for the Pardall Center's budget and events.
